//go:build !ignore_autogenerated

/*
Copyright 2025 RedbackThomson.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedProduct) DeepCopyInto(out *ObservedProduct) {
	*out = *in
	in.Initial.DeepCopyInto(&out.Initial)
	in.Current.DeepCopyInto(&out.Current)
	if in.Updates != nil {
		in, out := &in.Updates, &out.Updates
		*out = make([]ProductDetails, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CustomFields != nil {
		in, out := &in.CustomFields, &out.CustomFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedProduct.
func (in *ObservedProduct) DeepCopy() *ObservedProduct {
	if in == nil {
		return nil
	}
	out := new(ObservedProduct)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Product) DeepCopyInto(out *Product) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Product.
func (in *Product) DeepCopy() *Product {
	if in == nil {
		return nil
	}
	out := new(Product)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Product) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductDetails) DeepCopyInto(out *ProductDetails) {
	*out = *in
	if in.CompositeProductIDs != nil {
		in, out := &in.CompositeProductIDs, &out.CompositeProductIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CompositeTags != nil {
		in, out := &in.CompositeTags, &out.CompositeTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PresentationGroupKey != nil {
		in, out := &in.PresentationGroupKey, &out.PresentationGroupKey
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PricingGroupKey != nil {
		in, out := &in.PricingGroupKey, &out.PricingGroupKey
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.QuantityConversion != nil {
		in, out := &in.QuantityConversion, &out.QuantityConversion
		*out = new(QuantityConversion)
		**out = **in
	}
	if in.QuantityRounding != nil {
		in, out := &in.QuantityRounding, &out.QuantityRounding
		*out = new(QuantityRounding)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductDetails.
func (in *ProductDetails) DeepCopy() *ProductDetails {
	if in == nil {
		return nil
	}
	out := new(ProductDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductList) DeepCopyInto(out *ProductList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Product, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductList.
func (in *ProductList) DeepCopy() *ProductList {
	if in == nil {
		return nil
	}
	out := new(ProductList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProductList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductParameters) DeepCopyInto(out *ProductParameters) {
	*out = *in
	if in.BillableMetricRef != nil {
		in, out := &in.BillableMetricRef, &out.BillableMetricRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.BillableMetricSelector != nil {
		in, out := &in.BillableMetricSelector, &out.BillableMetricSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.CompositeProductIDs != nil {
		in, out := &in.CompositeProductIDs, &out.CompositeProductIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CompositeTags != nil {
		in, out := &in.CompositeTags, &out.CompositeTags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PresentationGroupKey != nil {
		in, out := &in.PresentationGroupKey, &out.PresentationGroupKey
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PricingGroupKey != nil {
		in, out := &in.PricingGroupKey, &out.PricingGroupKey
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.QuantityConversion != nil {
		in, out := &in.QuantityConversion, &out.QuantityConversion
		*out = new(QuantityConversion)
		**out = **in
	}
	if in.QuantityRounding != nil {
		in, out := &in.QuantityRounding, &out.QuantityRounding
		*out = new(QuantityRounding)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductParameters.
func (in *ProductParameters) DeepCopy() *ProductParameters {
	if in == nil {
		return nil
	}
	out := new(ProductParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductSpec) DeepCopyInto(out *ProductSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductSpec.
func (in *ProductSpec) DeepCopy() *ProductSpec {
	if in == nil {
		return nil
	}
	out := new(ProductSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProductStatus) DeepCopyInto(out *ProductStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProductStatus.
func (in *ProductStatus) DeepCopy() *ProductStatus {
	if in == nil {
		return nil
	}
	out := new(ProductStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantityConversion) DeepCopyInto(out *QuantityConversion) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantityConversion.
func (in *QuantityConversion) DeepCopy() *QuantityConversion {
	if in == nil {
		return nil
	}
	out := new(QuantityConversion)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuantityRounding) DeepCopyInto(out *QuantityRounding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuantityRounding.
func (in *QuantityRounding) DeepCopy() *QuantityRounding {
	if in == nil {
		return nil
	}
	out := new(QuantityRounding)
	in.DeepCopyInto(out)
	return out
}
