//go:build !ignore_autogenerated

/*
Copyright 2025 RedbackThomson.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillableMetric) DeepCopyInto(out *BillableMetric) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillableMetric.
func (in *BillableMetric) DeepCopy() *BillableMetric {
	if in == nil {
		return nil
	}
	out := new(BillableMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BillableMetric) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillableMetricList) DeepCopyInto(out *BillableMetricList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BillableMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillableMetricList.
func (in *BillableMetricList) DeepCopy() *BillableMetricList {
	if in == nil {
		return nil
	}
	out := new(BillableMetricList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BillableMetricList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillableMetricParameters) DeepCopyInto(out *BillableMetricParameters) {
	*out = *in
	in.EventTypeFilter.DeepCopyInto(&out.EventTypeFilter)
	if in.PropertyFilters != nil {
		in, out := &in.PropertyFilters, &out.PropertyFilters
		*out = make([]PropertyFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupKeys != nil {
		in, out := &in.GroupKeys, &out.GroupKeys
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.CustomFields != nil {
		in, out := &in.CustomFields, &out.CustomFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillableMetricParameters.
func (in *BillableMetricParameters) DeepCopy() *BillableMetricParameters {
	if in == nil {
		return nil
	}
	out := new(BillableMetricParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillableMetricSpec) DeepCopyInto(out *BillableMetricSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	if in.RollbackRetriesLimit != nil {
		in, out := &in.RollbackRetriesLimit, &out.RollbackRetriesLimit
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillableMetricSpec.
func (in *BillableMetricSpec) DeepCopy() *BillableMetricSpec {
	if in == nil {
		return nil
	}
	out := new(BillableMetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BillableMetricStatus) DeepCopyInto(out *BillableMetricStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BillableMetricStatus.
func (in *BillableMetricStatus) DeepCopy() *BillableMetricStatus {
	if in == nil {
		return nil
	}
	out := new(BillableMetricStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EventTypeFilter) DeepCopyInto(out *EventTypeFilter) {
	*out = *in
	if in.InValues != nil {
		in, out := &in.InValues, &out.InValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotInValues != nil {
		in, out := &in.NotInValues, &out.NotInValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EventTypeFilter.
func (in *EventTypeFilter) DeepCopy() *EventTypeFilter {
	if in == nil {
		return nil
	}
	out := new(EventTypeFilter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservedBillableMetric) DeepCopyInto(out *ObservedBillableMetric) {
	*out = *in
	in.EventTypeFilter.DeepCopyInto(&out.EventTypeFilter)
	if in.PropertyFilters != nil {
		in, out := &in.PropertyFilters, &out.PropertyFilters
		*out = make([]PropertyFilter, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GroupKeys != nil {
		in, out := &in.GroupKeys, &out.GroupKeys
		*out = make([][]string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
		}
	}
	if in.CustomFields != nil {
		in, out := &in.CustomFields, &out.CustomFields
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservedBillableMetric.
func (in *ObservedBillableMetric) DeepCopy() *ObservedBillableMetric {
	if in == nil {
		return nil
	}
	out := new(ObservedBillableMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyFilter) DeepCopyInto(out *PropertyFilter) {
	*out = *in
	if in.Exists != nil {
		in, out := &in.Exists, &out.Exists
		*out = new(bool)
		**out = **in
	}
	if in.InValues != nil {
		in, out := &in.InValues, &out.InValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.NotInValues != nil {
		in, out := &in.NotInValues, &out.NotInValues
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyFilter.
func (in *PropertyFilter) DeepCopy() *PropertyFilter {
	if in == nil {
		return nil
	}
	out := new(PropertyFilter)
	in.DeepCopyInto(out)
	return out
}
