apiVersion: metronome.crossplane.io/v1alpha1
kind: BillableMetric
metadata:
  name: example-metric
spec:
  providerConfigRef:
    name: provider-metronome
  forProvider:
    name: CPU Hours
    eventTypeFilter:
      inValues:
        - cpu_usage
    propertyFilters:
      - name: cpu_hours
        exists: True
      - name: region
        exists: True
        inValues:
          - EU
          - NA
      - name: machine_type
        exists: True
        inValues:
          - slow
          - fast
    aggregationType: sum
    aggregationKey: cpu_hours
    groupKeys:
        -
          - region
        -
          - machine_type
