apiVersion: metronome.crossplane.io/v1alpha1
kind: BillableMetric
metadata:
  name: example-metric
spec:
  providerConfigRef:
    name: provider-metronome
  forProvider:
    name: CPU Hours
    event_type_filter:
      in_values:
        - cpu_usage
    property_filters:
      - name: cpu_hours
        exists: True
      - name: region
        exists: True
        in_values:
          - EU
          - NA
      - name: machine_type
        exists: True
        in_values:
          - slow
          - fast
    aggregation_type: sum
    aggregation_key: cpu_hours
    group_keys:
        -
          - region
        -
          - machine_type
