// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !ignore_autogenerated

package converters

import (
	v1alpha1 "github.com/redbackthomson/provider-metronome/apis/customfieldkey/v1alpha1"
	metronome "github.com/redbackthomson/provider-metronome/internal/clients/metronome"
)

// +k8s:deepcopy-gen=false
type CustomFieldKeyConverterImpl struct{}

func (c *CustomFieldKeyConverterImpl) FromCustomFieldKey(source *metronome.CustomFieldKey) *v1alpha1.ObservedCustomFieldKey {
	var pV1alpha1ObservedCustomFieldKey *v1alpha1.ObservedCustomFieldKey
	if source != nil {
		var v1alpha1ObservedCustomFieldKey v1alpha1.ObservedCustomFieldKey
		v1alpha1ObservedCustomFieldKey.EnforceUniqueness = (*source).EnforceUniqueness
		v1alpha1ObservedCustomFieldKey.Entity = (*source).Entity
		v1alpha1ObservedCustomFieldKey.Key = (*source).Key
		pV1alpha1ObservedCustomFieldKey = &v1alpha1ObservedCustomFieldKey
	}
	return pV1alpha1ObservedCustomFieldKey
}
func (c *CustomFieldKeyConverterImpl) FromCustomFieldKeySpec(source *v1alpha1.CustomFieldKeyParameters) *metronome.CreateCustomFieldKeyRequest {
	var pMetronomeCreateCustomFieldKeyRequest *metronome.CreateCustomFieldKeyRequest
	if source != nil {
		var metronomeCreateCustomFieldKeyRequest metronome.CreateCustomFieldKeyRequest
		metronomeCreateCustomFieldKeyRequest.EnforceUniqueness = (*source).EnforceUniqueness
		metronomeCreateCustomFieldKeyRequest.Entity = (*source).Entity
		metronomeCreateCustomFieldKeyRequest.Key = (*source).Key
		pMetronomeCreateCustomFieldKeyRequest = &metronomeCreateCustomFieldKeyRequest
	}
	return pMetronomeCreateCustomFieldKeyRequest
}
func (c *CustomFieldKeyConverterImpl) FromCustomFieldKeyToParameters(source *metronome.CustomFieldKey) *v1alpha1.CustomFieldKeyParameters {
	var pV1alpha1CustomFieldKeyParameters *v1alpha1.CustomFieldKeyParameters
	if source != nil {
		var v1alpha1CustomFieldKeyParameters v1alpha1.CustomFieldKeyParameters
		v1alpha1CustomFieldKeyParameters.EnforceUniqueness = (*source).EnforceUniqueness
		v1alpha1CustomFieldKeyParameters.Entity = (*source).Entity
		v1alpha1CustomFieldKeyParameters.Key = (*source).Key
		pV1alpha1CustomFieldKeyParameters = &v1alpha1CustomFieldKeyParameters
	}
	return pV1alpha1CustomFieldKeyParameters
}
func (c *CustomFieldKeyConverterImpl) ToCustomFieldKey(source *v1alpha1.ObservedCustomFieldKey) *metronome.CustomFieldKey {
	var pMetronomeCustomFieldKey *metronome.CustomFieldKey
	if source != nil {
		var metronomeCustomFieldKey metronome.CustomFieldKey
		metronomeCustomFieldKey.EnforceUniqueness = (*source).EnforceUniqueness
		metronomeCustomFieldKey.Entity = (*source).Entity
		metronomeCustomFieldKey.Key = (*source).Key
		pMetronomeCustomFieldKey = &metronomeCustomFieldKey
	}
	return pMetronomeCustomFieldKey
}
func (c *CustomFieldKeyConverterImpl) ToCustomFieldKeySpec(source *metronome.CreateCustomFieldKeyRequest) *v1alpha1.CustomFieldKeyParameters {
	var pV1alpha1CustomFieldKeyParameters *v1alpha1.CustomFieldKeyParameters
	if source != nil {
		var v1alpha1CustomFieldKeyParameters v1alpha1.CustomFieldKeyParameters
		v1alpha1CustomFieldKeyParameters.EnforceUniqueness = (*source).EnforceUniqueness
		v1alpha1CustomFieldKeyParameters.Entity = (*source).Entity
		v1alpha1CustomFieldKeyParameters.Key = (*source).Key
		pV1alpha1CustomFieldKeyParameters = &v1alpha1CustomFieldKeyParameters
	}
	return pV1alpha1CustomFieldKeyParameters
}
